// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_dynamodb_all_tables_region": "us-east-1",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "Notes-ascendenv",
            "region": "us-east-1"
        }
    ],
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_3mQ4e7p9c",
    "aws_user_pools_web_client_id": "5dh6sbbbgljjh3jk3vrqv49h2o",
    "oauth": {},
    "aws_mobile_analytics_app_id": "d7b7b51dc96847fe8a86a42e6410dc39",
    "aws_mobile_analytics_app_region": "us-east-1"
};


export default awsmobile;
