// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    'aws_appsync_graphqlEndpoint': 'https://kogmzo44vffwbfl2zwkw3z6rpy.appsync-api.us-east-1.amazonaws.com/graphql',
    'aws_appsync_region': 'us-east-1',
    'aws_appsync_authenticationType': 'AMAZON_COGNITO_USER_POOLS',
    "ClientDatabasePrefix": "Ascend API_AMAZON_COGNITO_USER_POOLS",
    'aws_appsync_apiKey': 'da2-kzo67gnl3jfffmoqrgqh3c5kfi',
     identityPoolId: 'us-east-1:5403c63f-ea59-4eb1-b657-b91796a0259d', 
        region: 'us-east-1', 
        userPoolId: 'us-east-1_3mQ4e7p9c',
        userPoolWebClientId: 'kkp33s51diojpije83q04be35', 
};


export default awsmobile;
